### ISSUE TITLE
Glue implementation coverage for get_schema action

### ISSUE THREAD

**Issue by vmironichev-nix** [getmoto/moto#5816]
Hello, as of now Moto server does not support Glue get_schema API which is necessary to work with kafka-ui pluggable deserialisers using Glue Schema Registry, at the moment Moto server results with http 500 NotImplementedError. Do you have on your road map plans to cover get_schema action? Please let me know if you have questions. 

Thanks,
Valeriy

moto server logs:
```
2023-01-04T13:26:38.758748876Z 192.168.48.5 - - [04/Jan/2023 13:26:38] "POST / HTTP/1.1" 500 -
2023-01-04T13:26:38.759802427Z Error on request:
2023-01-04T13:26:38.759833757Z Traceback (most recent call last):
2023-01-04T13:26:38.759838946Z   File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 335, in run_wsgi
2023-01-04T13:26:38.759842498Z     execute(self.server.app)
2023-01-04T13:26:38.759846195Z   File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 322, in execute
2023-01-04T13:26:38.759849296Z     application_iter = app(environ, start_response)
2023-01-04T13:26:38.759851971Z   File "/usr/local/lib/python3.7/site-packages/moto/moto_server/werkzeug_app.py", line 241, in __call__
2023-01-04T13:26:38.759854539Z     return backend_app(environ, start_response)
2023-01-04T13:26:38.759856916Z   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
2023-01-04T13:26:38.759859647Z     return self.wsgi_app(environ, start_response)
2023-01-04T13:26:38.759862307Z   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2076, in wsgi_app
2023-01-04T13:26:38.759865178Z     response = self.handle_exception(e)
2023-01-04T13:26:38.759867655Z   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2023-01-04T13:26:38.759870278Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
2023-01-04T13:26:38.759872637Z   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
2023-01-04T13:26:38.759875101Z     response = self.full_dispatch_request()
2023-01-04T13:26:38.759877619Z   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1519, in full_dispatch_request
2023-01-04T13:26:38.759896821Z     rv = self.handle_user_exception(e)
2023-01-04T13:26:38.759899838Z   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2023-01-04T13:26:38.759903096Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
2023-01-04T13:26:38.759905972Z   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1517, in full_dispatch_request
2023-01-04T13:26:38.759908733Z     rv = self.dispatch_request()
2023-01-04T13:26:38.759911268Z   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1503, in dispatch_request
2023-01-04T13:26:38.759914027Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2023-01-04T13:26:38.759916781Z   File "/usr/local/lib/python3.7/site-packages/moto/core/utils.py", line 131, in __call__
2023-01-04T13:26:38.759920036Z     result = self.callback(request, request.url, dict(request.headers))
2023-01-04T13:26:38.759923133Z   File "/usr/local/lib/python3.7/site-packages/moto/core/responses.py", line 217, in dispatch
2023-01-04T13:26:38.759926531Z     return cls()._dispatch(*args, **kwargs)
2023-01-04T13:26:38.759929280Z   File "/usr/local/lib/python3.7/site-packages/moto/core/responses.py", line 356, in _dispatch
2023-01-04T13:26:38.759933235Z     return self.call_action()
2023-01-04T13:26:38.759936801Z   File "/usr/local/lib/python3.7/site-packages/moto/core/responses.py", line 458, in call_action
2023-01-04T13:26:38.759940398Z     "The {0} action has not been implemented".format(action)
2023-01-04T13:26:38.759943787Z NotImplementedError: The get_schema action has not been implemented
```

kafka-ui with pluggable deserialiser log:
```
023-01-04T13:26:39.289610234Z Error has been observed at the following site(s):
2023-01-04T13:26:39.289613425Z 	*__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289620059Z 	*__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289623281Z 	*__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289626949Z 	*__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289630742Z 	*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289634315Z 	*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289638498Z 	*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289642074Z 	*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289645699Z 	*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289649474Z 	*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289652879Z 	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
2023-01-04T13:26:39.289655478Z 	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
2023-01-04T13:26:39.289659310Z 	*__checkpoint ⇢ HTTP GET "/api/clusters/kafka-cluster/topic/test-topic/serdes?use=SERIALIZE" [ExceptionHandlingWebHandler]
```

**Comment by bblommers** [comment]
Hi @vmironichev-nix, welcome to Moto! There is no roadmap here - most features are added by the community, as and when they need it. PR's are always welcome, if you want to implement this yourself!
