### ISSUE TITLE
Updating object in versioned bucket leaks key

### ISSUE THREAD

**Issue by hannes-ucsc** [getmoto/moto#5956]
Continued from #5937

```python
python <<END
import warnings

from boto3 import client
from moto import (
    __version__,
    mock_s3,
)

warnings.simplefilter('error')

print(__version__)

for i in (1, 2):
    with mock_s3():
        s3 = client('s3')
        s3.create_bucket(Bucket='foo')
        s3.put_bucket_versioning(Bucket='foo',
                                 VersioningConfiguration={
                                     'Status': 'Enabled',
                                     'MFADelete': 'Disabled'
                                 })
        s3.put_object(Bucket='foo', Key='bar', Body='stuff')
        s3.put_object(Bucket='foo', Key='bar', Body='stuff2')
END
```

produces

```
4.1.3.dev33
Exception ignored in: <function FakeKey.__del__ at 0x1040cd1f0>
Traceback (most recent call last):
  File "/Users/…/.venv/lib/python3.9/site-packages/moto/s3/models.py", line 359, in __del__
    self.dispose(garbage=True)
  File "/Users/…/.venv/lib/python3.9/site-packages/moto/s3/models.py", line 349, in dispose
    warnings.warn("S3 key was not disposed of in time", ResourceWarning)
ResourceWarning: S3 key was not disposed of in time
```

**Comment by hannes-ucsc** [comment]
An earlier version of the repro used `mock_sts` and `mock_dynamodb`. Those aren't necessary but the loop at the top is.

**Comment by hannes-ucsc** [comment]
Looking good. All my tests pass without emitting any warnings now. Thank you!

**Comment by bblommers** [comment]
Happy to hear that! Thanks for confirming @hannes-ucsc
