### ISSUE TITLE
KMS key alias not supported in `re_encrypt` operation

### ISSUE THREAD

**Issue by rolandcrosby-dbt** [getmoto/moto#5963]
Thanks for the quick fix on #5957. I believe the same issue is happening with the `DestinationKeyId` argument for [`re_encrypt()`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kms.html#KMS.Client.re_encrypt):

```
>>> kms.re_encrypt(CiphertextBlob=ciphertext, DestinationKeyId="alias/foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rolandcrosby/src/scratch/venv/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/rolandcrosby/src/scratch/venv/lib/python3.8/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the ReEncrypt operation: Invalid keyId alias/foo
```

**Comment by bblommers** [comment]
Thanks for bringing this to our attention @rolandcrosby-dbt - this should now be fixed as of moto >= 4.1.4.dev13. Please let us know if you run into any other issues!
