### ISSUE TITLE
Cloudformation template (awslambda) throws unhashable type: 'dict'

### ISSUE THREAD

**Issue by hans-d** [getmoto/moto#6018]
The following
```
  template = {
    "Resources": {
      "olivedrabpeachpuffMoto396419EF": {
        "Type": "Custom::Whatever",
        "Properties": {
          "ServiceToken": {
            "Fn::GetAtt": [
              "MyNestedStackMotoProviderNestedStackResourceE0751832",
              "Outputs.stack0MotoProviderframeworkonEventCD7E7A58Arn"
            ]
          },
        },
      },
    },
  }

  boto_cloudformation_client.create_stack(StackName='test',
                                          TemplateBody=str(template))
```
results in

(pytest summary)
```
self = <moto.awslambda.models.LambdaStorage object at 0x1336d3ad0>
name = {'Fn::GetAtt': ['MyNestedStackMotoProviderNestedStackResourceE0751832', 'Outputs.stack0MotoProviderframeworkonEventCD7E7A58Arn']}
qualifier = None

    def get_function_by_name(
        self, name: str, qualifier: Optional[str] = None
    ) -> Optional[LambdaFunction]:
>       if name not in self._functions:
E       TypeError: unhashable type: 'dict'
```
Full traceback:
```
Traceback (most recent call last):
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/test.py", line 52, in test_template
    boto_cloudformation_client.create_stack(StackName='test',
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 307, in _should_retry
    return self._checker(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/endpoint.py", line 278, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/core/botocore_stubber.py", line 61, in __call__
    status, headers, body = response_callback(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/core/responses.py", line 229, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/core/responses.py", line 370, in _dispatch
    return self.call_action()
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/core/responses.py", line 459, in call_action
    response = method()
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/cloudformation/responses.py", line 148, in create_stack
    stack = self.cloudformation_backend.create_stack(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/cloudformation/models.py", line 910, in create_stack
    new_stack.create_resources()
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/cloudformation/models.py", line 491, in create_resources
    all_resources_ready = self.resource_map.create(self.template_dict)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/cloudformation/parsing.py", line 693, in create
    instance = self[resource]
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/cloudformation/parsing.py", line 514, in __getitem__
    new_resource = parse_and_create_resource(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/cloudformation/parsing.py", line 361, in parse_and_create_resource
    resource = resource_class.create_from_cloudformation_json(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/cloudformation/custom_model.py", line 53, in create_from_cloudformation_json
    fn = backend.get_function(service_token)
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/awslambda/models.py", line 1702, in get_function
    return self._lambdas.get_function_by_name_or_arn(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/awslambda/models.py", line 1294, in get_function_by_name_or_arn
    fn = self.get_function_by_name(name_or_arn, qualifier) or self.get_arn(
  File "/home/runner/moto-issue-cloudformation-unhashable-dict/venv/lib/python3.10/site-packages/moto/awslambda/models.py", line 1264, in get_function_by_name
    if name not in self._functions:
TypeError: unhashable type: 'dict'
```

Versions etc:
```
[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
replit = "^3.2.4"
pytest = "^7.2.2"
boto3 = "^1.26.84"
moto = {extras = ["cloudformation"], version = "^4.1.4"}
```

Full runnable code can be found at (Full example code at: https://replit.com/@HansDonner/moto-issue-cloudformation-unhashable-dict#test.py

**Comment by bblommers** [comment]
Hi @hans-d, just to double check - you are expecting a proper exception from Moto here, because the ServiceToken points to a non-existing ARN? 

It should work when pointing to another Lambda function in that template, but I'll do some digging to see why it behaves like it does for unknown ARN's.

**Comment by bblommers** [comment]
Note that will only ever work successfully  in ServerMode. The Lambda should notify CF that execution was successful, by sending an HTTP request, but that request can only be received if Moto runs as a server.

**Comment by hans-d** [comment]
Mainly concerned about the ` TypeError: unhashable type: 'dict'`.
This snipped comes from a live template (but redacted), part of a bigger assemble being generated (and works in a live environment).

Trying to work my way through getting the parts working with Moto.
