### ISSUE TITLE
Valid DynamoDB UpdateExpression Syntax Rejected with ValidationException

### ISSUE THREAD

**Issue by arohm-ff** [getmoto/moto#6074]
Looks like this might relate to #4580

### Problem Statement
I am working with some internal tables where we use attributes prefixed by the underscore character to indicate metadata fields on DynamoDB records. For example, the `_lastModified` attribute in the record below.
```
{
    "name": "Zelda",
    "released": "1985",
    "_lastModified": "2020-01-01T19:17:07.000000"
}
```
When testing out the `update_item` operation on a mocked DynamoDB table, I received a ValidationError (traceback below) indicating that the UpdateExpression formed to modify the `_lastModified` field was invalid syntax. 

### Expected Behavior
I expect the same syntax validation that runs in boto3 to apply to the statements that I run against mocked resources. In this case, if the syntax is valid, I would expect that moto processes the `update_item` call and updates the mocked table accordingly.

### Observed Behavior
When testing with moto, I get a ValidationError indicating that the UpdateExpression syntax is invalid. However, when testing against real DynamoDB resources, processing `update_item` requests containing the same syntax was allowed and processed successfully. 

### Tested versions:
I performed a clean install of boto3 and moto with the versions below using python 3.7, 3.8, 3.10 and saw the same failure on each
boto3 1.26.91 / botocore: 1.29.91
moto: 4.1.4

The version info below is from my regular working environment. I didn't do any sort of clean install, just observed the issue.
boto3 1.20.112 / botocore 1.17.112
moto: 2.2.15

### Traceback
```
Traceback (most recent call last):
  File "./test_dynamo_ops.py", line 23, in <module>
    ExpressionAttributeValues={":_lastModified": "YESTERDAY"}
  File "/Users/andrewrohm/Projects/moto/testenv/lib/python3.7/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/andrewrohm/Projects/moto/testenv/lib/python3.7/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/Users/andrewrohm/Projects/moto/testenv/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/andrewrohm/Projects/moto/testenv/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the UpdateItem operation: ExpressionAttributeNames contains invalid key: Syntax error; key: "#_lastModified"
```

### Steps to reproduce
The script included below will trigger the exception. When I rewrite it to target real AWS DynamoDB resources, no exception is generated and the update operation succeeds as expected.
```
import boto3
from moto import mock_dynamodb2
TABLE_NAME = "Games"
with mock_dynamodb2():
    mocked_dynamo_resource = boto3.resource("dynamodb", region_name="af-south-1")
    mocked_dynamo_resource.create_table(
        TableName=TABLE_NAME,
        KeySchema=[
            {"AttributeName": "id", "KeyType": "HASH"},
        ],
        AttributeDefinitions=[
            {"AttributeName": "id", "AttributeType": "S"},
        ],
        BillingMode="PAY_PER_REQUEST",
    )
    game_table = mocked_dynamo_resource.Table(TABLE_NAME)
    
    game_id = "ZELDA"
    game_response = game_table.update_item(
        Key={"id": game_id},
        UpdateExpression="set #_lastModified=:_lastModified",
        ExpressionAttributeNames={"#_lastModified": "_lastModified",},
        ExpressionAttributeValues={":_lastModified": "YESTERDAY"}
    )

    print(game_response)
```

**Comment by bblommers** [comment]
Thanks for raising this @arohm-ff - marking it as a bug!
