### ISSUE TITLE
AssertionError with SES Templates containing {

### ISSUE THREAD

**Issue by jritchie-nullable** [getmoto/moto#6206]
Reproduction of Issue 

run moto_server

Test Template (testTemplate.json): 
`{
  "Template": {
    "TemplateName": "Test",
    "SubjectPart": "Test",
    "HtmlPart": "This is a { Test } {{test}}",
    "TextPart": "This is a { Test } {{test}}"
  }
}`

aws ... ses create-template --cli-input-json file://./testTemplate.json
aws ... ses test-render-template --template-name Test --template-data '{"test":"test"}'

Internal Server Error is thrown.

StackTrace:
`127.0.0.1 - - [12/Apr/2023 13:53:29] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/werkzeug/serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/werkzeug/serving.py", line 320, in execute
    application_iter = app(environ, start_response)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/moto/moto_server/werkzeug_app.py", line 248, in __call__
    return backend_app(environ, start_response)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/moto/core/utils.py", line 106, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/moto/core/responses.py", line 231, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/moto/core/responses.py", line 372, in _dispatch
    return self.call_action()
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/moto/core/responses.py", line 461, in call_action
    response = method()
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/moto/ses/responses.py", line 270, in test_render_template
    rendered_template = self.backend.render_template(render_info)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/moto/ses/models.py", line 465, in render_template
    text_part = parse_template(str(text_part), template_data)
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/moto/ses/template.py", line 14, in parse_template
    tokenizer.skip_characters("{")
  File "/Users/jeff.ritchie/Library/Python/3.9/lib/python/site-packages/moto/utilities/tokenizer.py", line 51, in skip_characters
    assert self.expression[self.token_pos] in [ch.lower(), ch.upper()]
AssertionError`

This issue can be seen 
here: 
https://github.com/getmoto/moto/blob/c44f0b7395310d9ab63727633531281047292a5a/moto/ses/template.py#L13
and here:
https://github.com/getmoto/moto/blob/c44f0b7395310d9ab63727633531281047292a5a/moto/utilities/tokenizer.py#L51

I believe that the assumption was that if we encountered a { we were starting a template variable.

**Comment by bblommers** [comment]
Thanks for raising this @jritchie-nullable - marking it as a bug!
