### ISSUE TITLE
A Different Reaction of ECS tag_resource

### ISSUE THREAD

**Issue by taeho911** [getmoto/moto#6225]
Hello!
Let me report a bug found at `moto/ecs/models.py`.

# Symptom
When try to add new tags to a *_ECS cluster having no tag_*, `moto` fails to merge new tags into existing tags because of TypeError.

# Expected Result
The new tags should be added to the ECS cluster as `boto3` does.

# Code for Re-producing
```python
import boto3
from moto import mock_ecs

@mock_ecs
def test():
    client = boto3.client('ecs', region_name='us-east-1')
    res = client.create_cluster(clusterName='foo')
    arn = res['cluster']['clusterArn']
    client.tag_resource(resourceArn=arn, tags=[
        {'key': 'foo', 'value': 'foo'}
    ])

test()
```

# Traceback
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    test()
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/moto/core/models.py", line 124, in wrapper
    result = func(*args, **kwargs)
  File "test.py", line 9, in test
    client.tag_resource(resourceArn=arn, tags=[
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/retryhandler.py", line 307, in _should_retry
    return self._checker(
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/endpoint.py", line 278, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/moto/core/botocore_stubber.py", line 61, in __call__
    status, headers, body = response_callback(
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/moto/core/responses.py", line 231, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/moto/core/responses.py", line 372, in _dispatch
    return self.call_action()
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/moto/core/responses.py", line 461, in call_action
    response = method()
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/moto/ecs/responses.py", line 438, in tag_resource
    self.ecs_backend.tag_resource(resource_arn, tags)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/moto/ecs/models.py", line 2014, in tag_resource
    resource.tags = self._merge_tags(resource.tags, tags)
  File "/mnt/c/Users/kimdogg911/pjt/slack-bot/venv-test/lib/python3.8/site-packages/moto/ecs/models.py", line 2021, in _merge_tags
    for existing_tag in existing_tags:
TypeError: 'NoneType' object is not iterable
```

**Comment by bblommers** [comment]
Thanks for letting us know and providing the test case @taeho911! I'll raise a fix for this shortly.
