### ISSUE TITLE
werkzeug 2.3.3 resulting in 500 error in moto_server when creating iam.create_role or iam.get_role

### ISSUE THREAD

**Issue by Balasundaram** [getmoto/moto#6288]
Hello team,

I am using moto_server for running my aws lambda test cases. I create a role with mock_iam to use in the lambda function.

eg.
` 
iam.get_role(RoleName="my-role")["Role"]["Arn"]
iam.create_role(RoleName="my-role", AssumeRolePolicyDocument="some policy", Path="/my-path/",)["Role"]["Arn"]
`
This was working well but I am guessing after wekzueg latest version 2.3.3 release, we are having issue as below

`127.0.0.1 - - [05/May/2023 14:29:24] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/serving.py", line 325, in execute
    application_iter = app(environ, start_response)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/moto/moto_server/werkzeug_app.py", line 248, in __call__
    return backend_app(environ, start_response)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/moto/core/utils.py", line 106, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/moto/core/responses.py", line 231, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/moto/core/responses.py", line 371, in _dispatch
    self.setup_class(request, full_url, headers)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/moto/core/responses.py", line 249, in setup_class
    self.body = request.data
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/utils.py", line 106, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 376, in data
    return self.get_data(parse_form_data=True)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 426, in get_data
    self._load_form_data()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/flask/wrappers.py", line 114, in _load_form_data
    super()._load_form_data()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 274, in _load_form_data
    data = parser.parse(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/formparser.py", line 329, in parse
    return parse_func(stream, mimetype, content_length, options)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/formparser.py", line 377, in _parse_urlencoded
    stream.read().decode(),
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/wsgi.py", line 833, in readall
    data = self.read(1024 * 64)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/werkzeug/wsgi.py", line 814, in readinto
    b[:out_size] = data
TypeError: can assign only bytes, buffers, or iterables of ints in range(0, 256)
command terminated with exit code 137`

Since the werkzeug version is not pinned after moto 4.0.7, the latest version is getting installed and creating the above issue.

Any guidance is much appreciated.

Thanks
Bala

**Comment by yan12125** [comment]
FWIW, I got the same error (`TypeError: can assign only bytes, buffers, or iterables of ints in range(0, 256)`) with moto 4.1.8 and werkzeug 2.3.2. The error is gone after I switched to moto 4.1.9.dev27.

**Comment by Balasundaram** [comment]
Perfect @bblommers It works with 4.1.9. Thanks.
