### ISSUE TITLE
server: Overwriting a binary object in S3 causes `/moto-api/data.json` to fail

### ISSUE THREAD

**Issue by noelleleigh** [getmoto/moto#6407]
- **Moto version:** 759f26c6d (git cloned)
- **Python version:** 3.11.4
- **OS:** macOS 13.4

After storing a binary file in S3 on the server and overwriting it, the server's dashboard fails to load due to an unhandled exception while fetching `/moto-api/data.json`.

## Steps to reproduce

1. Start moto server

   ```shell
   $ python -m moto.server 
   WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
    * Running on http://127.0.0.1:5000
   Press CTRL+C to quit
   ```

1. In another terminal, create an S3 bucket:

   ```shell
   $ aws --endpoint-url http://localhost:5000/ s3 mb s3://bucket
   make_bucket: bucket
   ```

1. Store a binary file in the bucket twice under the same key:

   ```shell
   echo -n $'\x01' | aws --endpoint-url http://localhost:5000/ s3 cp - s3://bucket/blob
   echo -n $'\x02' | aws --endpoint-url http://localhost:5000/ s3 cp - s3://bucket/blob
   ```

1. Open the [Moto server dashboard](http://localhost:5000/moto-api/) or make a request to <http://127.0.0.1:5000/moto-api/data.json>:

   ```shell
   $ curl http://127.0.0.1:5000/moto-api/data.json
   <!doctype html>
   <html lang=en>
   <title>500 Internal Server Error</title>
   <h1>Internal Server Error</h1>
   <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
   ```

1. Check the server logs in the first terminal to see the stack trace:

   ```python
   127.0.0.1 - - [14/Jun/2023 10:45:55] "GET /moto-api/data.json HTTP/1.1" 500 -
   Error on request:
   Traceback (most recent call last):
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/werkzeug/serving.py", line 364, in run_wsgi
       execute(self.server.app)
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/werkzeug/serving.py", line 325, in execute
       application_iter = app(environ, start_response)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/moto/moto_server/werkzeug_app.py", line 250, in __call__
       return backend_app(environ, start_response)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
       return self.wsgi_app(environ, start_response)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
       response = self.handle_exception(e)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 165, in wrapped_function
       return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                   ^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
       response = self.full_dispatch_request()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
       rv = self.handle_user_exception(e)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 165, in wrapped_function
       return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                   ^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
       rv = self.dispatch_request()
            ^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
       return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/moto/core/utils.py", line 106, in __call__
       result = self.callback(request, request.url, dict(request.headers))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/moto/moto_api/_internal/responses.py", line 70, in model_data
       json.dumps(getattr(instance, attr))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/noelle/dev/moto/moto/s3/models.py", line 165, in value
       self._value_buffer.seek(0)
     File "/Users/noelle/.pyenv/versions/3.11.4/lib/python3.11/tempfile.py", line 808, in seek
       return self._file.seek(*args)
              ^^^^^^^^^^^^^^^^^^^^^^
   ValueError: I/O operation on closed file.
   ```

Expected behavior: The Moto server dashboard works as intended.

Actual behavior: The Moto server dashboard fails to display any information.

**Comment by bblommers** [comment]
Thanks for raising this and for adding the repro steps @noelleleigh - that's very helpful. I've created a PR with a fix.
