### ISSUE TITLE
batch.create_compute_environment() call fails against moto server

### ISSUE THREAD

**Issue by RealSalmon-Komodo** [getmoto/moto#6463]
When calling `create_compute_environment()` for Batch against the server version of moto, a 500 response is returned. I have pasted a script to replicate the issue below, along with the output I am seeing.

To replicate, run the following...

```python
# Set the BOTO3_ENDPOINT env var in order to specify the moto server endpoint URL

import logging
import os
import boto3

logging.basicConfig()
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

endpoint_url = os.environ.get('BOTO3_ENDPOINT')


def boto3_client(service):
    return boto3.client(service, endpoint_url=endpoint_url)


batch = boto3_client('batch')
ec2 = boto3_client('ec2')
iam = boto3_client('iam')

# IAM Role
logger.debug('creating IAM role...')
role_name = 'best-role-evar'
response = iam.create_role(RoleName=role_name, AssumeRolePolicyDocument='yadda')
role_arn = response['Role']['Arn']
logger.debug('IAM role created as %s', role_arn)

# VPC and Subnets
logger.debug('creating VPC...')
response = ec2.create_vpc(CidrBlock='10.0.0.0/16')
vpc_id = response['Vpc']['VpcId']
logger.debug('VPC created with ID %s', vpc_id)

logger.debug('creating VPC Subnet...')
response = ec2.create_subnet(VpcId=vpc_id, CidrBlock='10.0.0.0/20')
subnet_ids = [response['Subnet']['SubnetId']]
logger.debug('VPC subnet created with ID %s', subnet_ids[0])

# Batch compute environment
logger.debug('creating Batch compute environment...')
response = batch.create_compute_environment(
    computeEnvironmentName='ec2-env',
    type='MANAGED',
    state="ENABLED",
    computeResources={
        'type': 'EC2',
        'maxvCpus': 1,
        'subnets': subnet_ids
    },
    serviceRole=role_arn
)
logger.debug('Batch compute environment created')
```
... here is the output I am seeing from the above when running against the latest Docker image of moto server ...

```
DEBUG:__main__:creating IAM role...
DEBUG:__main__:IAM role created as arn:aws:iam::123456789012:role/best-role-evar
DEBUG:__main__:creating VPC...
DEBUG:__main__:VPC created with ID vpc-24efcf33
DEBUG:__main__:creating VPC Subnet...
DEBUG:__main__:VPC subnet created with ID subnet-d3426728
DEBUG:__main__:creating Batch compute environment...
Traceback (most recent call last):
  File "/var/project/moto-batch.py", line 42, in <module>
    response = batch.create_compute_environment(
  File "/var/task/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (500) when calling the CreateComputeEnvironment operation (reached max retries: 4): <!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by bblommers** [comment]
Hey @RealSalmon-Komodo, thanks for raising this. Looks like AWS throws an error in this scenario because the `Instance role is required` - we'll add the same validation to Moto.
