### ISSUE TITLE
A cognito user should not be able to login if his account is disabled

### ISSUE THREAD

**Issue by quirozs** [getmoto/moto#6552]
A user should not be able to login into his account if said account is disabled, it should raise a: `NotAuthorizedException` with the message: `User is disabled.`. Instead, it continues with a normal successful login (if credentials are correct).

## How to reproduce
Using python mocks
- Python 3.10.12
- Moto 4.1.13
- boto3 1.26.90
- botocore 1.29.165
```python
import boto3

from moto import mock_cognitoidp

@mock_cognitoidp
def example():
    cognito = boto3.client("cognito-idp", "us-east-2")
    username = "fried"
    password = "password123"
    
    # Create user pool and client
    user_pool_id = cognito.create_user_pool(PoolName="FriedPool")["UserPool"]["Id"]
    client_id = cognito.create_user_pool_client(
        UserPoolId=user_pool_id,
        ClientName="FriedClient",
    )["UserPoolClient"]["ClientId"]

    # Create a user and disable the account
    cognito.admin_create_user(
        UserPoolId=user_pool_id,
        Username=username,
        TemporaryPassword=password,
    )
    cognito.admin_disable_user(
        UserPoolId=user_pool_id,
        Username=username,
    )

    # User should not be able to login into a disabled account
    response = cognito.admin_initiate_auth(
        UserPoolId=user_pool_id,
        ClientId=client_id,
        AuthFlow="ADMIN_USER_PASSWORD_AUTH",
        AuthParameters={"USERNAME": username, "PASSWORD": password},
    )
    print(response)


if __name__ == "__main__":
    example()
```
## Expected output
```
Traceback (most recent call last):
    File "/var/task/example.py", line 30, in example
        response = cognito.admin_initiate_auth(
    File "/var/runtime/botocore/client.py", line 530, in _api_call
        return self._make_api_call(operation_name, kwargs)
    File "/var/runtime/botocore/client.py", line 960, in _make_api_call
        raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotAuthorizedException: An error occurred (NotAuthorizedException) when calling the AdminInitiateAuth operation: User is disabled.
```
## Actual output
Login is successful
```
{'ChallengeName': 'NEW_PASSWORD_REQUIRED', 'Session': 'ff808d75-f2a0-496a-bbcf-1d0e0762e977', 'ChallengeParameters': {}, 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'date': 'Sat, 22 Jul 2023 01:09:43 GMT'}, 'RetryAttempts': 0}}
```

**Comment by quirozs** [comment]
I created this quick PR #6553 that solves this issue, any feedback is appreciated
