### ISSUE TITLE
SES send_raw_email() fails with MessageRejected exception

### ISSUE THREAD

**Issue by jenstroeger** [getmoto/moto#6596]
First of all, thank you for this interesting and great package!

I just stumbled upon an issue, and hope you can help me out. The following test:
```python
import pytest

import boto3
import moto

def test_ses(monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv("AWS_ACCESS_KEY_ID", "testing")
    monkeypatch.setenv("AWS_SECRET_ACCESS_KEY", "testing")
    monkeypatch.setenv("AWS_SECURITY_TOKEN", "testing")
    monkeypatch.setenv("AWS_SESSION_TOKEN", "testing")
    monkeypatch.setenv("AWS_DEFAULT_REGION", "us-east-1")

    with moto.mock_ses():
        client = boto3.client("ses")
        client.send_raw_email(
            Destinations=["test@foo.com"],
            Source="from@from.com",
            RawMessage={
                "Data": "",
            },
        )
```
fails with this exception:
```
Traceback (most recent call last):
  [ ... ]
  File "/path/to/test/tests/test_ses.py", line 16, in test_ses
    client.send_raw_email(
  File "/path/to/test/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/path/to/test/.venv/lib/python3.10/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MessageRejected: An error occurred (MessageRejected) when calling the SendRawEmail operation: Did not have authority to send from email from@from.com
```
This is with Moto v4.1.14 and Boto3 v1.28.19/Botocore v1.31.19.

Am I missing something? Looking at [the docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ses/client/send_raw_email.html) I am unsure if need to mock/set up a sending authority here, i.e. the `AWS_BLA` environment variables with certain mock values?

**Comment by jenstroeger** [comment]
@bblommers that helped, works like a charm! Thank you!
