### ISSUE TITLE
[MultiAccount] S3 Bucket created by another account can be retrieved by list_objects_v2

### ISSUE THREAD

**Issue by sukekyo26** [getmoto/moto#6622]
test.py
```python
from moto import mock_s3
import boto3
import os

@mock_s3
def s3_test():
    s3 = boto3.client("s3")
    # Create test_1 bucket with account ID 111111111111
    os.environ["MOTO_ACCOUNT_ID"] = "111111111111"
    s3.create_bucket(Bucket="test_1")
    del os.environ["MOTO_ACCOUNT_ID"]

    # Create test_2 bucket with account ID 222222222222
    os.environ["MOTO_ACCOUNT_ID"] = "222222222222"
    s3.create_bucket(Bucket="test_2")
    del os.environ["MOTO_ACCOUNT_ID"]

    # account ID 111111111111
    os.environ["MOTO_ACCOUNT_ID"] = "111111111111"
    print("-----------------------------------list_buckets-----------------------------------")
    print(s3.list_buckets())
    print("-----------------------------------list_objects_v2(test_2)-----------------------------------")
    print(s3.list_objects_v2(Bucket="test_2")) # I can get it.
    print("-----------------------------------list_objects_v2(test_3)-----------------------------------")
    print(s3.list_objects_v2(Bucket="test_3")) # Error
    del os.environ["MOTO_ACCOUNT_ID"]

if __name__ == "__main__":
    s3_test()
```
Prompt
```bash
(3.9.16_test) user:~/work/test$ python test.py 
-----------------------------------list_buckets-----------------------------------
{'ResponseMetadata': {'RequestId': 'P6umhB4GbfwW1mnscmdu29mkl2vtmUJ0MWCOxGbNJnO4GvP0xqoD', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'P6umhB4GbfwW1mnscmdu29mkl2vtmUJ0MWCOxGbNJnO4GvP0xqoD'}, 'RetryAttempts': 0}, 'Buckets': [{'Name': 'test_1', 'CreationDate': datetime.datetime(2023, 8, 9, 9, 57, 47, tzinfo=tzutc())}], 'Owner': {'DisplayName': 'webfile', 'ID': 'bcaf1ffd86f41161ca5fb16fd081034f'}}
-----------------------------------list_objects_v2(test_2)-----------------------------------
{'ResponseMetadata': {'RequestId': 'AizBBbtp0lOfuHoWbDqT7HDIoqLrF0E0MXMLAB29Cl37PSHWJFsy', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'AizBBbtp0lOfuHoWbDqT7HDIoqLrF0E0MXMLAB29Cl37PSHWJFsy'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Name': 'test_2', 'Prefix': '', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 0}
-----------------------------------list_objects_v2(test_3)-----------------------------------
Traceback (most recent call last):
  File "/home/user/work/test/test.py", line 29, in <module>
    s3_test()
  File "/home/user/.pyenv/versions/3.9.16_test/lib/python3.9/site-packages/moto/core/models.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/work/test/test.py", line 25, in s3_test
    print(s3.list_objects_v2(Bucket="test_3")) # Error
  File "/home/user/.pyenv/versions/3.9.16_test/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/user/.pyenv/versions/3.9.16_test/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
(3.9.16_test) user:~/work/test$ 
```
Hi
The above code creates a test_1 bucket with account ID 11111111111111 and a test_2 bucket with account ID 222222222222.
If the account ID is 111111111111 and the list_buckets method is executed, only the test_1 bucket can be retrieved.
But if I specify the test_2 bucket in the list_objects_v2 method, I can retrieve it.
If I specify the test_3 bucket which is not created by any account in the list_objects_v2 method , I get an error.
test_2 should also result in a NoSuchBucket error.
Sorry if this is a duplicate of a similar issue.

version:
python 3.9.16
boto3==1.28.22
botocore==1.31.22
moto==4.1.14

**Comment by bblommers** [comment]
Hi @sukekyo26!

This is by design, actually - all our cross-account access is allowed by default. 

The overall philosophy is to only deny access if there is an IAM policy that explicitly says so.

Note that this isn't implemented for S3 yet, but if you can share a bit more about your use case, we can always look at how we can implement this.

**Comment by sukekyo26** [comment]
@bblommers 
Thanks for the detailed explanation. I understood that it was designed.
I don't have the source code at hand, so here is a simplified example of what I was trying to do.

my_func.py
```python
import boto3

def my_func():
    # This function runs in a stg environment
    # stg environment account id 「"111111111111"」
    # prd environment account id 「"222222222222"」
    create_prefix = "test/"
    account_prd = "222222222222"
    sts = boto3.client("sts")
    response = sts.assume_role(
        RoleArn=f"arn:aws:iam::{account_prd}:role/my-role",
        RoleSessionName="session-name"
    )

    s3_stg = boto3.client("s3")
    s3_prd = boto3.client(
        "s3",
        aws_access_key_id=response["Credentials"]["AccessKeyId"],
        aws_secret_access_key=response["Credentials"]["SecretAccessKey"],
        aws_session_token=response["Credentials"]["SessionToken"]
    )

    # Check for the existence of the prefix test/.
    res_test_stg = s3_stg.list_objects_v2(Bucket="stg_bucket", Prefix=create_prefix)
    res_test_prd = s3_prd.list_objects_v2(Bucket="prd_bucket", Prefix=create_prefix)

    if not res_test_stg.get("Contents") and not res_test_prd.get("Contents"):
        template_prefix = "template/"
        res_stg = s3_stg.list_objects_v2(Bucket="stg_bucket", Prefix=template_prefix)
        for obj in res_stg.get('Contents', []):
            key = obj['Key']
            new_key = key.replace(template_prefix, create_prefix, 1)

            s3_stg.copy_object(
                CopySource={'Bucket': "stg_bucket", 'Key': key},
                Bucket="stg_bucket",
                Key=new_key
            )

        res_prd = s3_prd.list_objects_v2(Bucket="prd_bucket", Prefix=template_prefix)
        for obj in res_prd.get('Contents', []):
            key = obj['Key']
            new_key = key.replace(template_prefix, create_prefix, 1)

            s3_prd.copy_object(
                CopySource={'Bucket': "prd_bucket", 'Key': key},
                Bucket="prd_bucket",
                Key=new_key
            )

if __name__ == "__main__":
    my_func()
``` 
test_my_func.py
```python
import os
import boto3
import pytest
import my_func
from moto import mock_s3, mock_sts

def test_my_func(
    mock_aws,
    create_bucket,
    create_template_html
):
    # execute my_func
    my_func.my_func()

    s3 = boto3.client("s3")

    # Check that test/test.html has been created
    res_stg = s3.list_objects_v2(Bucket="stg_bucket", Prefix="test/")
    assert res_stg["Contents"][0]["Key"] == "test/test.html"

@pytest.fixture(scope="function")
def mock_aws():
    print("start mock_aws")
    s3_mock = mock_s3()
    sts_mock = mock_sts()
    s3_mock.start()
    sts_mock.start()
    yield
    print("end mock_aws")
    s3_mock.stop()
    sts_mock.stop()

@pytest.fixture(scope="function")
def create_bucket():
    print("start create_bucket")
    s3 = boto3.client("s3")

    # Create stg_bucket bucket with stg environment(stg's account id is 11111111111111 but moto's default account id is 123456789012, so moto's default account is considered as stg)
    s3.create_bucket(Bucket="stg_bucket")

    # Create prd_bucket bucket with prd environment
    os.environ["MOTO_ACCOUNT_ID"] = "222222222222"
    s3.create_bucket(Bucket="prd_bucket")
    del os.environ["MOTO_ACCOUNT_ID"]

    yield
    print("end create_bucket")
    # Deletion process of bucket (omitted here)

@pytest.fixture(scope="function")
def create_template_html():
    print("start create_template_html")
    s3 = boto3.client("s3")
    s3_object_key = 'template/test.html'
    file_content = 'test'

    # Create template/test.html with stg environment
    s3.put_object(Body=file_content, Bucket="stg_bucket", Key=s3_object_key)

    # Create template/test.html with prd environment
    os.environ["MOTO_ACCOUNT_ID"] = "222222222222"
    s3.put_object(Body=file_content, Bucket="prd_bucket", Key=s3_object_key)
    del os.environ["MOTO_ACCOUNT_ID"]

    yield
    print("end create_template_html")
    # Deletion process of file (omitted here)
``` 

I use moto to test functions like my_func.py above.
First, there is a stg_bucket bucket in stg_account (111111111111) and a prd_bucket in prd_account (222222222222). These buckets have the same internal configuration and have a prefix of template/ directly under them.

The process flow is
Check existence of contents of create_prefix(test/) in both stg_bucket of stg_account and prd_bucket of prd_account by using list_object_v2 method.
↓
If it does not exist, copy the files under template/ to test/ for both stg_bucket of stg_account and prd_bucket of prd_account .

The test code creates template/test.html in stg_backet and prd_backet in advance, and confirms that test/test.html is created after the process is executed.
However, I mistakenly used s3_prd as s3_stg in line 25 of my_func.py, but did not notice the mistake because the test passed.Where I thought it would be NoSuchBucket.

Sorry it took so long.
I'd like to see this implemented in S3 if possible.

**Comment by bblommers** [comment]
Thank you for the explanation @sukekyo26 - that makes sense.

I'm thinking of introducing a new environment variable for this, something like `MOTO_S3_CROSSACCOUNT_ACCESS` that is set to `true` by default.
From what I can tell, that's easiest to implement for us, and easiest to configure for users.

A more AWS-focused solution might be to set ACL's explicitly deny access, but that puts the burden on the user to create correct ACL's to replicate AWS behaviour. So that's a lot of configuration/setup, replicated for every user, just to get the 'expected' behaviour.

**Comment by bblommers** [comment]
Hi @sukekyo26, this is now part of moto >= 4.2.1.dev27.

You can set the following environment variable to enable this validation:
```
MOTO_S3_ALLOW_CROSSACCOUNT_ACCESS=false
```
See the documentation here: http://docs.getmoto.org/en/latest/docs/services/s3.html

Note that I've opted to throw a `AccessDenied` error, instead of a `NoSuchBucket`. That is more in-line with how AWS behaves when trying to request a bucket that you don't have access to.

**Comment by sukekyo26** [comment]
Hi @bblommers 

thank you very much!!
I will try using it!
