### ISSUE TITLE
Not all methods in mock_databrew work when Dataset has spaces in the name

### ISSUE THREAD

**Issue by frank-hopkin-accrisoft** [getmoto/moto#6921]
## Symptom

Not all methods in mock_databrew work when Dataset has spaces in the name. For example, list_datasets works after I run create_dataset . However, delete_dataset **and** update_dataset do not work after I run create_dataset . I have been using the naming convention for live resources and am able to create and delete them without issue.

### Specs
OS: Ubuntu 22.04.3 LTS
Python: 3.10.12
boto3: 1.28.62
botocore: 1.31.62
moto: 4.2.6

### Dockerfile
```Dockerfile
FROM ubuntu:22.04

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install python3 python3-pip -y
RUN /usr/bin/python3 -m pip install botocore boto3 boto moto python-jose -y
```

### test.py
```py
from moto import mock_databrew
import boto3

@mock_databrew
def test_delete_dataset():
    databrew_client = boto3.client("databrew")
    stringone = 'testId'
    stringtwo = 'testTable'

    rsp_cre = databrew_client.create_dataset(
        Name=stringone + ' - ' + stringtwo,
        Format='CSV',
        FormatOptions={
            'Csv': {
                'Delimiter': ',',
                'HeaderRow': True
            }
        },
        Input={
            'S3InputDefinition': {
                'Bucket': 'my_import_bucket',
                'Key': stringone + '/import/' + stringtwo + '/data.csv',
            }
        }
    )
    print("=== Create Result ===")
    print(rsp_cre)
    print("")
    
    
    rsp_list = databrew_client.list_datasets()
    print("=== List Result ===")
    print(rsp_list.get("Datasets")[0])
    print("")
    
    rsp_del = databrew_client.delete_dataset(
        Name=rsp_cre.get('Name')
    )
    
    print("=== Delete Result ===")
    print(rsp_del.get('Name'))
    print("")
    
    
test_delete_dataset()
```

## Expected Behavior
```
# /usr/bin/python3 test.py
=== Create Result ===
testId - testTable

=== List Result ===
{'CreateDate': datetime.datetime(2023, 10, 15, 19, 19, 42, 247000, tzinfo=tzlocal()), 'Name': 'testId - testTable', 'Format': 'CSV', 'FormatOptions': {'Csv': {'Delimiter': ',', 'HeaderRow': True}}, 'Input': {'S3InputDefinition': {'Bucket': 'my_import_bucket', 'Key': 'testId/import/testTable/data.csv'}}, 'Tags': {}, 'ResourceArn': 'arn:aws:databrew:us-east-1:123456789012:dataset/testId - testTable'}

=== Delete Result ===
testId - testTable
```

## Actual Behavior
```
# /usr/bin/python3 test.py
=== Create Result ===
testId - testTable

=== List Result ===
{'CreateDate': datetime.datetime(2023, 10, 15, 19, 19, 42, 247000, tzinfo=tzlocal()), 'Name': 'testId - testTable', 'Format': 'CSV', 'FormatOptions': {'Csv': {'Delimiter': ',', 'HeaderRow': True}}, 'Input': {'S3InputDefinition': {'Bucket': 'my_import_bucket', 'Key': 'testId/import/testTable/data.csv'}}, 'Tags': {}, 'ResourceArn': 'arn:aws:databrew:us-east-1:123456789012:dataset/testId - testTable'}

Traceback (most recent call last):
  File "/home/user/test.py", line 45, in <module>
    test_delete_dataset()
  File "/home/user/.local/lib/python3.10/site-packages/moto/core/models.py", line 128, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/test.py", line 36, in test_delete_dataset
    rsp_del = databrew_client.delete_dataset(
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DeleteDataset operation: One or more resources can't be found.
```

## Note
First time submitting GitHub issue that I can remember. If you need anything additional please just let me know.

### AWS documentation
https://docs.aws.amazon.com/databrew/latest/dg/API_CreateDataset.html#databrew-CreateDataset-request-Name
States spaces are valid

### pytest failure output
Remove the last line from the code snippet before running via pytest
```
pytest /home/user/test.py
============================================= test session starts =============================================
platform linux -- Python 3.10.12, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/user
collected 0 items / 1 error                                                                                   

=================================================== ERRORS ====================================================
__________________________________________ ERROR collecting test.py ___________________________________________
/usr/local/lib/python3.10/dist-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
/usr/local/lib/python3.10/dist-packages/_pytest/runner.py:372: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
/usr/local/lib/python3.10/dist-packages/_pytest/python.py:531: in collect
    self._inject_setup_module_fixture()
/usr/local/lib/python3.10/dist-packages/_pytest/python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
/usr/local/lib/python3.10/dist-packages/_pytest/python.py:310: in obj
    self._obj = obj = self._getobj()
/usr/local/lib/python3.10/dist-packages/_pytest/python.py:528: in _getobj
    return self._importtestmodule()
/usr/local/lib/python3.10/dist-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/usr/local/lib/python3.10/dist-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
test.py:45: in <module>
    test_delete_dataset()
../.local/lib/python3.10/site-packages/moto/core/models.py:128: in wrapper
    result = func(*args, **kwargs)
test.py:36: in test_delete_dataset
    rsp_del = databrew_client.delete_dataset(
/usr/local/lib/python3.10/dist-packages/botocore/client.py:535: in _api_call
    return self._make_api_call(operation_name, kwargs)
/usr/local/lib/python3.10/dist-packages/botocore/client.py:980: in _make_api_call
    raise error_class(parsed_response, operation_name)
E   botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DeleteDataset operation: One or more resources can't be found.
----------------------------------------------- Captured stdout -----------------------------------------------
=== Create Result===
testId - testTable

=== List Result===
{'CreateDate': datetime.datetime(2023, 10, 15, 19, 32, 25, 390000, tzinfo=tzlocal()), 'Name': 'testId - testTable', 'Format': 'CSV', 'FormatOptions': {'Csv': {'Delimiter': ',', 'HeaderRow': True}}, 'Input': {'S3InputDefinition': {'Bucket': 'my_import_bucket', 'Key': 'testId/import/testTable/data.csv'}}, 'Tags': {}, 'ResourceArn': 'arn:aws:databrew:us-east-1:123456789012:dataset/testId - testTable'}

=========================================== short test summary info ===========================================
ERROR test.py - botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when callin...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================== 1 error in 0.76s ===============================================
```

**Comment by bblommers** [comment]
Thanks for raising this @frank-hopkin-accrisoft - I'll submit a PR with a fix shortly.
