### ISSUE TITLE
unable to search a specific version from the modelPackage

### ISSUE THREAD

**Issue by anupash147** [getmoto/moto#6970]
### Objective:
To get a specific version of model from the modelPackge dito to this command
```
list_model_packages(ModelPackageGroupName='fooBar',
                                                    ModelApprovalStatus='Approved',
                                                    **MaxResults=2,**
                                                    SortBy='CreationTime',
                                                    SortOrder='Descending'
```
                                                    
### Failing with reason:
```Traceback (most recent call last):
  File "/Users/Library/CloudStorage/OneDrive/Projects/redact/tests/model/test_model_repository.py", line 88, in setUp
    pprint(self.sg.list_model_packages(ModelPackageGroupName='fooBar',
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/client.py", line 963, in _make_api_call
    http, parsed_response = self._make_request(
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/client.py", line 986, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/retryhandler.py", line 307, in _should_retry
    return self._checker(
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/endpoint.py", line 278, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/moto/core/botocore_stubber.py", line 61, in __call__
    status, headers, body = response_callback(
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/moto/core/responses.py", line 245, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/moto/core/responses.py", line 446, in _dispatch
    return self.call_action()
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/moto/core/responses.py", line 539, in call_action
    response = method()
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/moto/sagemaker/responses.py", line 846, in list_model_packages
    ) = self.sagemaker_backend.list_model_packages(
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/moto/utilities/paginator.py", line 61, in pagination_wrapper
    return paginator.paginate(results)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/moto/utilities/paginator.py", line 184, in paginate
    next_token = self._build_next_token(last_resource_on_this_page)
  File "/Users/miniconda3/envs/myenv/lib/python3.9/site-packages/moto/utilities/paginator.py", line 156, in _build_next_token
    range_keys.append(str(getattr(next_item, attr)))
AttributeError: 'ModelPackage' object has no attribute 'ModelPackageArn'
```

### Sample code to recreate the bug:

```
class testModelRepository(unittest.TestCase):

    def setUp(self):
        """
        Setting up patches/ mock for all defs in the test class
        :return:
        """
    
        self.mock_sagemaker = mock_sagemaker()
        self.mock_sagemaker.start()
    
        # create sagemaker and upload model packages
        self.sg = boto3.client("sagemaker")
        self.sg.create_model_package_group(
            ModelPackageGroupName='fooBar',
            ModelPackageGroupDescription='first model'
        )
        self.sg.create_model_package_group(
            ModelPackageGroupName='fooJill',
            ModelPackageGroupDescription='Second model'
        )
        for x in range(10):
            self.sg.create_model_package(
                ModelPackageName='foo-Bar-xyz',
                ModelPackageGroupName='fooBar',
                ModelPackageDescription='this is model package version',
                InferenceSpecification={
                    'Containers': [
                        {'Image': '683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3',
                         'ImageDigest': 'sha256:f2c3cb8da7ebce475c43a84a2567db54418462a542f6d15b8ea9df23dbbd763e',
                         'ModelDataUrl': 's3://afadfsdfadsfasdf/TrainModel-ztnJXxBsLI/output/model.tar.gz',
                         'Environment': {}}],
                    'SupportedTransformInstanceTypes': [
                        'ml.m5.large',
                    ],
                    'SupportedRealtimeInferenceInstanceTypes': [
                        'ml.t2.medium', 'ml.m5.large',
                    ],
                    'SupportedContentTypes': [
                        'text/csv',
                    ],
                    'SupportedResponseMIMETypes': [
                        'text/csv',
                    ]
                },
                CertifyForMarketplace=False,
                Tags=[
                    {
                        'Key': 'string',
                        'Value': 'string'
                    },
                ],
                ModelApprovalStatus='Approved',
                MetadataProperties={'Repository': 'xyz'},
                ModelMetrics={
                    'ModelQuality': {
                        'Statistics': {
                            'ContentType': 'string',
                            'ContentDigest': 'string',
                            'S3Uri': 'string'
                        },
                        'Constraints': {
                            'ContentType': 'string',
                            'ContentDigest': 'string',
                            'S3Uri': 'string'
                        }
                    }
                }
            )
        from pprint import pprint
        pprint(self.sg.list_model_packages(ModelPackageGroupName='fooBar',
                                                                      ModelApprovalStatus='Approved',
                                                                      MaxResults=2,      <====
                                                                      SortBy='CreationTime',
                                                                      SortOrder='Descending'
                                                                      )['ModelPackageSummaryList'])
```

The same code will succeed if you omit `MaxResults` or use `MaxResults=10`

On deep observation i found that the model versions {...} are created in duplicate, to clarify. when you execute the following code

```
   self.sg.create_model_package( ....
```
2 sets of dictionary objects are created
```
{'CreationTime': datetime.datetime(2023, 10, 30, 19, 50, 2, 913750, tzinfo=tzutc()),
 'ModelApprovalStatus': 'Approved',
 'ModelPackageArn': 'arn:aws:sagemaker:us-east-1:123456789012:model-package/foo-bar-xyz/1',
 'ModelPackageDescription': 'this is model package version',
 'ModelPackageGroupName': 'fooBar',
 'ModelPackageName': 'foo-Bar-xyz',
 'ModelPackageStatus': 'Completed',
 'ModelPackageVersion': 1}
{'CreationTime': datetime.datetime(2023, 10, 30, 19, 50, 2, 923927, tzinfo=tzutc()),
 'ModelApprovalStatus': 'Approved',
 'ModelPackageArn': 'arn:aws:sagemaker:us-east-1:123456789012:model-package/foo-bar-xyz/1',
 'ModelPackageDescription': 'this is model package version',
 'ModelPackageGroupName': 'fooBar',
 'ModelPackageName': 'foo-Bar-xyz',
 'ModelPackageStatus': 'Completed',
 'ModelPackageVersion': 1}
```

So believe this needs to be fixed

**Comment by bblommers** [comment]
Hi @anupash147, thanks for letting us know. I'll raise a PR shortly for the pagination bug.

Can you expand a bit on the duplicate model versions? How are you reproducing it?
When I tested this, I couldn't see anything strange.

**Comment by anupash147** [comment]
> Hi @anupash147, thanks for letting us know. I'll raise a PR shortly for the pagination bug.
> 
> Can you expand a bit on the duplicate model versions? How are you reproducing it? When I tested this, I couldn't see anything strange.

I did run the same code i provided checkout the pprint code that displays the dictionary
<img width="693" alt="image" src="https://github.com/getmoto/moto/assets/8271182/780879d9-391f-46b3-bb53-ff8aedf3e544">
try this
```
x = self.sg.list_model_packages(ModelPackageGroupName='fooBar',
                                                                      ModelApprovalStatus='Approved',
                                                                      SortBy='CreationTime',
                                                                      SortOrder='Descending'
                                                                      )['ModelPackageSummaryList'])
print(x[0])
```

**Comment by bblommers** [comment]
The behaviour makes me think that your print-statement is inside the for-loop. So that's why you're seeing the same print-statement multiple times.

**Comment by bblommers** [comment]
I don't think there's anything else for Moto here, so I'll close this. Let us know if you run into any other issues.
