### ISSUE TITLE
KeyError in _lookup_expression_attribute_value

### ISSUE THREAD

**Issue by tomers** [getmoto/moto#6979]
Moto version: `4.2.8.dev`

The following command
```
aws --endpoint-url http://localhost:5000 dynamodb scan --table-name tsh-ip-bans scan --filter-expression "location1 = :loc" --expression-attribute-values '{"loc": {"S": "mgmt"}}'
```
Results in the following error:
```
172.17.0.1 - - [01/Nov/2023 12:37:18] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/moto_server/werkzeug_app.py", line 260, in __call__
    return backend_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/core/utils.py", line 108, in __call__
    result = self.callback(request, request.url, dict(request.headers))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/core/responses.py", line 245, in dispatch
    return cls()._dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/core/responses.py", line 446, in _dispatch
    return self.call_action()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/utilities/aws_headers.py", line 46, in _wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/utilities/aws_headers.py", line 74, in _wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/responses.py", line 197, in call_action
    response = getattr(self, endpoint)()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/responses.py", line 51, in _wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/responses.py", line 791, in scan
    items, scanned_count, last_evaluated_key = self.dynamodb_backend.scan(
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/models/__init__.py", line 365, in scan
    filter_expression_op = get_filter_expression(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/comparisons.py", line 23, in get_filter_expression
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/comparisons.py", line 193, in parse
    nodes = self._parse_paths(nodes)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/comparisons.py", line 323, in _parse_paths
    children = [self._parse_path_element(name) for name in path]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/comparisons.py", line 323, in <listcomp>
    children = [self._parse_path_element(name) for name in path]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/comparisons.py", line 392, in _parse_path_element
    value=self._lookup_expression_attribute_value(name),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/dynamodb/comparisons.py", line 427, in _lookup_expression_attribute_value
    return self.expression_attribute_values[name]  # type: ignore[index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: ':loc'
```

How to reproduce:
First, run the `moto` docker:
```
docker run --rm -p 5000:5000 --name moto motoserver/moto:latest
```
Then:
```
aws --endpoint-url http://localhost:5000 \
    dynamodb create-table \
    --table-name tsh-ip-bans \
    --attribute-definitions \
        AttributeName=location,AttributeType=S \
        AttributeName=sort_key,AttributeType=S \
    --key-schema \
        AttributeName=location,KeyType=HASH \
        AttributeName=sort_key,KeyType=RANGE \
    --provisioned-throughput \
        ReadCapacityUnits=10,WriteCapacityUnits=5 \
        > /dev/null

sleep 1

aws --endpoint-url http://localhost:5000 \
    dynamodb scan \
    --table-name tsh-ip-bans \
    scan --filter-expression "location1 = :loc" --expression-attribute-values '{"loc": {"S": "mgmt"}}'
```

**Comment by bblommers** [comment]
Thanks for raising this and for providing the repro @tomers - that's really useful.

I'll do some testing against AWS, but I presume that they would throw an error here because `:loc` is not defined as part of the `expression-attribute-values`.
Marking it as an enhancement to add the same validation, and to throw the same exception.
