### ISSUE TITLE
DynamoDB UpdateExpression with newlines raises InvalidTokenException 

### ISSUE THREAD

**Issue by abbasyadollahi** [getmoto/moto#7127]
### Context

When calling an API that uses `UpdateExpression`, the `ExpressionTokenizer` raises an `InvalidTokenException` if the expression contains newlines, even though it should be an acceptable expression. This seems similar to the issue #2275, but from what I see the tokenizer's changed quite a lot since then.

It looks like moto raises the following exception when executing this [line](https://github.com/getmoto/moto/blob/4.2.11/moto/dynamodb/parsing/tokens.py#L210).

```
moto.dynamodb.exceptions.InvalidTokenException: 400 Bad Request: {"__type": "com.amazonaws.dynamodb.v20120810#ValidationException", "message": "Invalid UpdateExpression: Syntax error; token: \"\n\", near: \"\n\""}
```

I think the solution could be as simple as adding a newline token and grouping it in with the whitespaces (it worked for me), though I haven't ran tests against it.

### Example

The boto client is able to write the item without any issues, whereas the moto client fails with the following stacktrace.

```
Traceback (most recent call last):
  File "/Users/abbasyadollahi/random/issue.py", line 48, in <module>
    query(moto_client) # This raises
    ^^^^^^^^^^^^^^^^^^
  File "/Users/abbasyadollahi/random/issue.py", line 10, in query
    client.update_item(
  File "/Users/abbasyadollahi/random/env/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abbasyadollahi/random/env/lib/python3.11/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the UpdateItem operation: Invalid UpdateExpression: Syntax error; token: "
", near: "ADD
"
```

```python
import boto3
import moto

table_name = "test"
my_key = "my_key"
my_count = "1"


def query(client):
    client.update_item(
        TableName=table_name,
        Key={
            "MyKey": {"S": my_key},
        },
        UpdateExpression=(
            """
            ADD
                MyTotalCount :MyCount
            """
        ),
        ExpressionAttributeValues={
            ":MyTotalCount": {"N": my_count},
        },
    )


boto_client = boto3.client("dynamodb")
query(boto_client)  # This passes

with moto.mock_dynamodb():
    moto_client = boto3.client("dynamodb")
    moto_client.create_table(
        TableName=table_name,
        KeySchema=[
            {
                "AttributeName": "MyKey",
                "KeyType": "HASH",
            }
        ],
        AttributeDefinitions=[
            {
                "AttributeName": "MyKey",
                "AttributeType": "S",
            }
        ],
        BillingMode="PAY_PER_REQUEST",
    )
    query(moto_client)  # This raises
```

### Versions

boto3==1.34.0
botocore==1.34.0
moto==4.2.11

**Comment by bblommers** [comment]
Hi @abbasyadollahi, welcome to Moto! I'll mark this as a bug.
