### ISSUE TITLE
How to create user when using ThreadedMotoServer in version 5.0.0?

### ISSUE THREAD

**Issue by homper** [getmoto/moto#7302]
I have s3 client written in C that connects with https to s3 server.
For tests I want to use standalone moto server with self-signed ssl certificate.
So I coppied and changed ThreadedMotoServer to take ssl_context as an argument (MotoServerSSL in [the code below](#example)).

To create user and its credentials I was using this code
```py
	@classmethod
	@set_initial_no_auth_action_count(4)
	def setUpClass(cls):
		...
		cls.s3_server = MotoServerSSL(ssl_context=cls.ssl_key)
		cls.s3_server.start()
		cls.iam_server = MotoServerSSL(port=cls.iam_port,
		                               service='iam',
		                               ssl_context=cls.ssl_key)
		cls.iam_server.start()

		iam_config = Config(signature_version=UNSIGNED)
		iam = boto3.client('iam',
		                   config=iam_config,
		                   endpoint_url=f"https://{cls.host}:{cls.iam_port}",
		                   verify=cls.ssl_key[0])
		iam.create_user(UserName=cls.user)
		...
		response = iam.create_access_key(UserName=cls.user)
		cls.access_key_id = response["AccessKey"]["AccessKeyId"]
		cls.secret_access_key = response["AccessKey"]["SecretAccessKey"]
```

I understand that this is probably over complicated and wrong but I couldn't find any documented way to do this at the time.

This code worked for version 4.2.14
```sh
pip3 install 'moto[s3]==4.2.14' --upgrade
```
But service attribute was removed from DomainDispatcherApplication in version 5 and this workaround doesn't work anymore
```sh
pip3 install 'moto[s3]==5.0.0' --upgrade
```

**So is there a right way to create user for ThreadedMotoServer?**

I was trying
```py
	@classmethod
	@set_initial_no_auth_action_count(4)
	def setUpClass(cls):
        ...
		cls.s3_server = MotoServerSSL(ssl_context=cls.ssl_key)
		cls.s3_server.start()

		iam_config = Config(signature_version=UNSIGNED)

		iam = boto3.client('iam',
		                   config=iam_config,
		                   endpoint_url=f"https://{cls.host}:{cls.port}/iam_{cls.region}/", # so it can find out service from url
		                   verify=cls.ssl_key[0])
		iam.create_user(UserName=cls.user)
        ...
		response = iam.create_access_key(UserName=cls.user)
		cls.access_key_id = response["AccessKey"]["AccessKeyId"]
		cls.secret_access_key = response["AccessKey"]["SecretAccessKey"]
```

But I got an error
```
======================================================================
ERROR: setUpClass (t.s3_test.S3Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/botocore/parsers.py", line 505, in _parse_xml_string_to_dom
    parser.feed(xml_string)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/moto/core/responses.py", line 209, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/redacted/projects/orioledb/t/s3_test.py", line 47, in setUpClass
    iam.create_user(UserName=cls.user)
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 199, in _send_request
    success_response, exception = self._get_response(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 241, in _get_response
    success_response, exception = self._do_get_response(
                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 308, in _do_get_response
    parsed_response = parser.parse(
                      ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/parsers.py", line 250, in parse
    parsed = self._do_error_parse(response, shape)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/parsers.py", line 559, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/parsers.py", line 508, in _parse_xml_string_to_dom
    raise ResponseParserError(
botocore.parsers.ResponseParserError: Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'<!doctype html>\n<html lang=en>\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n'

----------------------------------------------------------------------
Ran 0 tests in 0.248s

FAILED (errors=1)
```

# Example
Adding an example test code. Simplified as far as possible.
### s3_test.py
```python
#!/usr/bin/env python3
# coding: utf-8

import unittest
import json
import logging
import os
import time
from tempfile import mkstemp
from threading import Thread
from typing import Optional

import boto3
from botocore import UNSIGNED
from botocore.config import Config
from moto.core import set_initial_no_auth_action_count
from moto.server import DomainDispatcherApplication, create_backend_app

from werkzeug.serving import BaseWSGIServer, make_server, make_ssl_devcert
import urllib3

log = logging.getLogger('werkzeug')
log.setLevel(logging.ERROR)

# Copied ThreadedMotoServer so custom ssl_context and service can be used
class MotoServerSSL:

	def __init__(self,
	             host: str = "localhost",
	             port: int = 5002,
	             service: Optional[str] = None,
	             ssl_context=None):
		self._host = host
		self._port = port
		self._service = service
		self._thread: Optional[Thread] = None
		self._server: Optional[BaseWSGIServer] = None
		self._server_ready = False
		self._ssl_context = ssl_context

	def _server_entry(self) -> None:
		app = DomainDispatcherApplication(create_backend_app, self._service)

		self._server = make_server(self._host,
		                           self._port,
		                           app,
		                           False,
		                           ssl_context=self._ssl_context,
		                           passthrough_errors=True)
		self._server_ready = True
		self._server.serve_forever()

	def start(self) -> None:
		self._thread = Thread(target=self._server_entry, daemon=True)
		self._thread.start()
		while not self._server_ready:
			time.sleep(0.1)

	def stop(self) -> None:
		self._server_ready = False
		if self._server:
			self._server.shutdown()

		self._thread.join()  # type: ignore[union-attr]

class S3Test(unittest.TestCase):
	bucket_name = "test-bucket"
	host = "localhost"
	port = 5002
	iam_port = 5001
	user = "TEST_USER"
	region = "us-east-1"

	@classmethod
	@set_initial_no_auth_action_count(4)
	def setUpClass(cls):
		urllib3.util.connection.HAS_IPV6 = False
		cls.ssl_key = make_ssl_devcert('/tmp/test_key', cn=cls.host)
		cls.s3_server = MotoServerSSL(ssl_context=cls.ssl_key)
		cls.s3_server.start()
		cls.iam_server = MotoServerSSL(port=cls.iam_port,
		                               service='iam',
		                               ssl_context=cls.ssl_key)
		cls.iam_server.start()

		iam_config = Config(signature_version=UNSIGNED)

		iam = boto3.client('iam',
		                   config=iam_config,
		                   endpoint_url=f"https://{cls.host}:{cls.iam_port}",
		                   verify=cls.ssl_key[0])
		iam.create_user(UserName=cls.user)
		policy_document = {
		    "Version": "2012-10-17",
		    "Statement": {
		        "Effect": "Allow",
		        "Action": "*",
		        "Resource": "*"
		    }
		}
		policy = iam.create_policy(PolicyName="TEST_POLICY",
		                           PolicyDocument=json.dumps(policy_document))
		policy_arn = policy["Policy"]["Arn"]
		iam.attach_user_policy(UserName=cls.user, PolicyArn=policy_arn)
		response = iam.create_access_key(UserName=cls.user)
		cls.access_key_id = response["AccessKey"]["AccessKeyId"]
		cls.secret_access_key = response["AccessKey"]["SecretAccessKey"]

	def test_s3_put_get(self):
		# Here I'm using boto but in my test I have S3 client written in C
		# where I use credentials and ssl_key generated in setUpClass

		session = boto3.Session(aws_access_key_id=self.access_key_id,
		                        aws_secret_access_key=self.secret_access_key,
		                        region_name=self.region)
		self.client = session.client("s3",
		                             endpoint_url=f"https://{self.host}:{self.port}",
		                             verify=self.ssl_key[0])
		self.client.create_bucket(Bucket=self.bucket_name)

		file_body = "HELLO\nIT'S A ME\nMARIO\n"
		fd, s3_test_file = mkstemp()
		with os.fdopen(fd, 'wt') as fp:
			fp.write(file_body)

		self.client.upload_file(Bucket=self.bucket_name,
		                        Filename=s3_test_file,
		                        Key="mario")
		objects = self.client.list_objects(Bucket=self.bucket_name)
		objects = objects.get("Contents", [])
		objects = sorted(list(x["Key"] for x in objects))
		self.assertEqual(objects, ['mario'])

		object = self.client.get_object(Bucket=self.bucket_name,
		                                Key='mario')
		boto_object_body = object["Body"].readlines()
		boto_object_body = [x.decode("utf-8") for x in boto_object_body]
		boto_object_body = ''.join(boto_object_body)
		self.assertEqual(boto_object_body, file_body)
		os.unlink(s3_test_file)

		objects = self.client.list_objects(Bucket=self.bucket_name)
		objects = objects.get("Contents", [])
		while objects != []:
			objects = list({"Key": x["Key"]} for x in objects)
			self.client.delete_objects(Bucket=self.bucket_name,
			                           Delete={"Objects": objects})
			objects = self.client.list_objects(Bucket=self.bucket_name)
			objects = objects.get("Contents", [])

		self.client.delete_bucket(Bucket=self.bucket_name)
		self.client.close()

	@classmethod
	def tearDownClass(cls):
		cls.s3_server.stop()
		cls.iam_server.stop()
```

Then I runned it like this:
```sh
python3 -m unittest s3_test.py
```

# specs:
```
neofetch --off
...
OS: macOS 12.7 21G816 x86_64
Host: MacBookPro11,4
Kernel: 21.6.0
Uptime: 3 hours, 13 mins
Packages: 206 (brew)
Shell: zsh 5.8.1
Resolution: 1440x900
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Dark)
Terminal: Apple_Terminal
Terminal Font: SFMono-Regular
CPU: Intel i7-4770HQ (8) @ 2.20GHz
GPU: Intel Iris Pro
Memory: 9414MiB / 16384MiB
```
```
python3 --version
Python 3.11.7
```
```
pip3 list | grep boto
boto3              1.34.32
boto3-stubs        1.34.29
botocore           1.34.32
botocore-stubs     1.34.29
mypy-boto3-iam     1.34.8
mypy-boto3-s3      1.34.14
```

**Comment by bblommers** [comment]
Hi @homper! Just to clarify - you have removed the `service`-argument to the DomainDispatcher? As it's still there in the example test.

I would expect it to work without that argument:
```
class MotoServerSSL:

	def __init__(self,
	             host: str = "localhost",
	             port: int = 5002,
	             service: Optional[str] = None,
	             ssl_context=None): 
                ....

	def _server_entry(self) -> None:
		app = DomainDispatcherApplication(create_backend_app)
                ...
```

Just as an FYI - the reason it was removed is because it was unnecessary. The MotoServer uses the incoming request to determine which module it should connect to (iam, s3, dynamodb, whatever), so there is no reason to explicitly specify it when starting the server.

**Comment by bblommers** [comment]
Had to spend some time to debug, but I see the problem now. Like I said, he MotoServer uses the incoming request to determine which module it should connect to - and more specifically, it mainly uses the Authentication-header, as that contains the service-name.

Because the requests are explicitly unsigned, the request does not have an Authentication-header, so Moto doesn't know what to do with it.
> iam_config = Config(signature_version=UNSIGNED)

I'm assuming you have something similar specified in the original C-code. What is the reason behind that part?

If your system doesn't have any AWS credentials configured, you could set environment variables with some bogus values to use:
```
export AWS_ACCESS_KEY_ID=what
export AWS_SECRET_ACCESS_KEY=ever
```

The AWS SDK will use those bogus values to generate a valid Authentication-header, and Moto will 'magically' understand the incoming requests again.

**Comment by homper** [comment]
No I was creating user only with boto, not in my program.
I was sending UNSIGNED request with set_initial_no_auth_action_count for the server side because I thought that I have no user at the moment. I didn't know that you can use even empty credentials to create one.

Thank you for information
So now I understand that I can just write it like this
```py
	@classmethod
	def setUpClass(cls):
		...
		iam = boto3.client('iam',
		                   endpoint_url=f"https://{cls.host}:{cls.port}",
						   aws_access_key_id="",
						   aws_secret_access_key="",
						   region_name=cls.region,
		                   verify=cls.ssl_key[0])
		iam.create_user(UserName=cls.user)
		...
		response = iam.create_access_key(UserName=cls.user)
		cls.access_key_id = response["AccessKey"]["AccessKeyId"]
		cls.secret_access_key = response["AccessKey"]["SecretAccessKey"]

```

**Comment by bblommers** [comment]
Yes, that works indeed. Happy to hear it's solved!
