### ISSUE TITLE
GetRoleCredentials operation: Not yet implemented when trying to passthrough secretsmanager

### ISSUE THREAD

**Issue by istrupin** [getmoto/moto#7304]
I am attempting to passthrough a call to secretsmanager to get a real secret from AWS, but then mock a few other services.  Unfortunately, it seems like when boto3 is attempting to get credentials, something inside of moto is causing an error.  

I'm using moto version 5.0.0, installed via pip (well -- poetry but regardless..), and am using a decorator.

As you can see from my decorator config, I've tried to passthrough a number of different services but with no luck.

What I want is for my actual secret in AWS to be retrieved.

Instead, I get the error below.

One relevant thing of note is that I am using AWS SSO -- so perhaps moto doesn't work well with that yet? I would imagine that shouldn't be an issue though.

Code:

```
moto_config = {
    "iam": {"load_aws_managed_policies": True},
    "core": {
        "mock_credentials": False,
        "passthrough": {
            "urls": [
                "https://secretsmanager.us-west-2.amazonaws.com/",
                "https://iam.amazonaws.com/",
                "https://sts.amazonaws.com/",
                "https://sso.amazonaws.com/",
                "https://identitystore.amazonaws.com/",
            ],
            "services": [
                "secretsmanager",
                "iam",
                "sts",
                "sso",
                "identitystore",
                "sso-admin",
            ],
        },
    },
}

@mock_aws(config=moto_config)
def run_function():
     secret = _get_secret("some_secret_name")
     ...


def _get_secret(secret_name):
    secretsmanager = _get_secretsmanager()
    response = secretsmanager.get_secret_value(SecretId=secret_name)
    return response

def _get_secretsmanager() -> SecretsManagerClient:
    AWS_PROFILE = os.getenv("PROFILE")
    session = boto3.Session(profile_name=AWS_PROFILE)
    return session.client("secretsmanager")

```

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/client.py", line 963, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/client.py", line 989, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/lib/python3.11/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/lib/python3.11/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/signers.py", line 180, in sign
    auth = self.get_auth_instance(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/signers.py", line 284, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/credentials.py", line 614, in get_frozen_credentials
    self._refresh()
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/credentials.py", line 502, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/credentials.py", line 518, in _protected_refresh
    metadata = self._refresh_using()
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/credentials.py", line 665, in fetch_credentials
    return self._get_cached_credentials()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/credentials.py", line 675, in _get_cached_credentials
    response = self._get_credentials()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/credentials.py", line 2140, in _get_credentials
    response = client.get_role_credentials(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/.venv/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/istrupin/code/spec-runner/Users/istrupin/code/spec-runner/lib/python3.11/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the GetRoleCredentials operation: Not yet implemented

**Comment by bblommers** [comment]
Hi @istrupin! It is due to the SSO, actually. I see that you did add `SSO` to the list of services to passthrough, so the `GetRoleCredentials`-operation should reach out to AWS. But because Moto doesn't support the SSO-service yet, we don't know which URL's to passthrough.

Does it work if you add the URL for the SSO-service explicitly to the list?
```
"urls": [
    ...,
    "https://portal.sso.us-west-2.amazonaws.com/",  # Adjust region as necessary..
    ...
```

**Comment by istrupin** [comment]
@bblommers  thanks so much for responding so quickly!

Adding the URL did get me further -- so that's awesome.  I really appreciate your help there, thank you so much!

Now I'm getting a different error where the secret doesn't exist when I have the decorator applied, but it works fine when I remove the decorator.

This is progress at least!


> File "/Users/istrupin/spec-runner/.venv/lib/python3.11/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret.

**Comment by istrupin** [comment]
@bblommers  thank you so much for your help!  That does make sense -- I incorrectly assumed that I could still use that service name, even if it wasn't implemented!

Looks like I'm all set.  Thanks for responding so quickly!  I truly appreciate it!

**Comment by bblommers** [comment]
No problem @istrupin - happy to hear this is solved! 

I'll close this, but let us know if you run into any other issues.
