### ISSUE TITLE
Call `GetId` on Cognito Identity when Access Control is available

### ISSUE THREAD

**Issue by nonchan7720** [getmoto/moto#7320]
Authorization may not be included in some Cognito operations.
Not including Authorization results in an error when Access control is enabled.

moto server version: 4.2.14

stack trace.
```
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/moto_server/werkzeug_app.py", line 262, in __call__
    return backend_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/core/utils.py", line 111, in __call__
    result = self.callback(request, request.url, dict(request.headers))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/core/responses.py", line 254, in dispatch
    return cls()._dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/core/responses.py", line 455, in _dispatch
    return self.call_action()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/core/responses.py", line 538, in call_action
    self._authenticate_and_authorize_normal_action(resource)
  File "/usr/local/lib/python3.11/site-packages/moto/core/responses.py", line 172, in _authenticate_and_authorize_normal_action
    self._authenticate_and_authorize_action(IAMRequest, resource)
  File "/usr/local/lib/python3.11/site-packages/moto/core/responses.py", line 156, in _authenticate_and_authorize_action
    iam_request = iam_request_cls(
                  ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/moto/iam/access_control.py", line 191, in __init__
    "Credential=", ",", self._headers["Authorization"]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/werkzeug/datastructures/headers.py", line 493, in __getitem__
    return self.environ[f"HTTP_{key}"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'HTTP_AUTHORIZATION'
```

**Comment by bblommers** [comment]
Hi @nonchan7720, thanks for raising this. I've identified the following operations where this problem could occur:

- "AWSCognitoIdentityProviderService.ConfirmSignUp"
- "AWSCognitoIdentityProviderService.GetUser"
- "AWSCognitoIdentityProviderService.ForgotPassword"
- "AWSCognitoIdentityProviderService.InitiateAuth"
- "AWSCognitoIdentityProviderService.SignUp"

They have now all been fixed with #7331 

Please let us know if we've missed anything.

**Comment by bblommers** [comment]
Ah, that's my  bad @nonchan7720. I only looked at the operations for CognitoIdentityProvider, but `GetId` falls under CognitoIdentity. 

#7335 should fix that (for real this time).

**Comment by nonchan7720** [comment]
Can you release it in v4?
I haven't been able to migrate to v5 yet, so I don't want to be released with v5... 🙇

**Comment by bblommers** [comment]
@nonchan7720 No, I'm not planning any V4 releases anymore

**Comment by nonchan7720** [comment]
Okay.
