### ISSUE TITLE
Unable to get backend for bedrock-agent

### ISSUE THREAD

**Issue by JoshLevyMN** [getmoto/moto#7458]
I am trying to run the scaffolding script to generate methods for bedrock-agents, and the first time the script is run, it will generate that function without an error, but when the scaffolding continues to run or if you try to generate any more functions after, it will give the following error:

``` 
python scripts/scaffold.py

This script uses the click-module.

 - Start typing the name of the service you want to extend
 - Use Tab to auto-complete the first suggest service
 - Use the up and down-arrows on the keyboard to select something from the dropdown
 - Press enter to continue

Select service: bedrock-agent
==Current Implementation Status==
[ ] associate_agent_knowledge_base
[ ] create_agent
[ ] create_agent_action_group
[ ] create_agent_alias
[ ] create_data_source
[ ] create_knowledge_base
[ ] delete_agent
[ ] delete_agent_action_group
[ ] delete_agent_alias
[ ] delete_agent_version
[ ] delete_data_source
[ ] delete_knowledge_base
[ ] disassociate_agent_knowledge_base
[ ] get_agent
[ ] get_agent_action_group
[ ] get_agent_alias
[ ] get_agent_knowledge_base
[ ] get_agent_version
[ ] get_data_source
[ ] get_ingestion_job
[ ] get_knowledge_base
[ ] list_agent_action_groups
[ ] list_agent_aliases
[ ] list_agent_knowledge_bases
[ ] list_agent_versions
[ ] list_agents
[ ] list_data_sources
[ ] list_ingestion_jobs
[ ] list_knowledge_bases
[ ] list_tags_for_resource
[ ] prepare_agent
[ ] start_ingestion_job
[ ] tag_resource
[ ] untag_resource
[ ] update_agent
[ ] update_agent_action_group
[ ] update_agent_alias
[ ] update_agent_knowledge_base
[ ] update_data_source
[ ] update_knowledge_base
=================================
Select Operation: create_knowledge_base
        Initializing service    bedrock-agent
        creating        moto/bedrockagent
        creating        moto/bedrockagent/models.py
        creating        moto/bedrockagent/exceptions.py
        creating        moto/bedrockagent/__init__.py
        creating        moto/bedrockagent/responses.py
        creating        moto/bedrockagent/urls.py
        creating        tests/test_bedrockagent
        creating        tests/test_bedrockagent/__init__.py
        creating        tests/test_bedrockagent/test_server.py
        creating        tests/test_bedrockagent/test_bedrockagent.py
        inserting code  moto/bedrockagent/responses.py
        inserting code  moto/bedrockagent/models.py
        inserting code  tests/test_bedrockagent/test_bedrockagent.py
Updating backend index...

Please select another operation, or Ctrl-X/Ctrl-C to cancel.

Remaining steps after development is complete:
- Run scripts/implementation_coverage.py,


Traceback (most recent call last):
  File "/Users/josh/dev/moto-bedrock-agent/moto/scripts/scaffold.py", line 668, in <module>
    main()
  File "/Users/josh/dev/moto-bedrock-agent/moto/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josh/dev/moto-bedrock-agent/moto/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/josh/dev/moto-bedrock-agent/moto/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josh/dev/moto-bedrock-agent/moto/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josh/dev/moto-bedrock-agent/moto/scripts/scaffold.py", line 639, in main
    operation = select_operation(service)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josh/dev/moto-bedrock-agent/moto/scripts/scaffold.py", line 81, in select_operation
    implemented, operation_names = get_operations(service_name)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josh/dev/moto-bedrock-agent/moto/scripts/scaffold.py", line 98, in get_operations
    moto_client, _name = get_moto_implementation(service_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josh/dev/moto-bedrock-agent/moto/scripts/implementation_coverage.py", line 21, in get_moto_implementation
    else backends[0]["global"]
         ~~~~~~~~~~~^^^^^^^^^^
  File "/Users/josh/dev/moto-bedrock-agent/moto/moto/core/base_backend.py", line 290, in __getitem__
    return super().__getitem__(region_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'global'
```

A similar error occurs when creating trying to run a function in bedrockagent during testing:
```
@mock_aws
    def test_create_agent():
        client = boto3.client("bedrock-agent", region_name=DEFAULT_REGION)
>       resp = client.create_agent(
            agentName="test-agent",
            agentResourceRoleArn="test-agent-arn",
            tags={
                    "Key": "test-tag-key",
                }
        )

tests/test_bedrockagent/test_bedrockagent.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.venv/lib/python3.12/site-packages/botocore/client.py:554: in _api_call
    return self._make_api_call(operation_name, kwargs)
.venv/lib/python3.12/site-packages/botocore/client.py:990: in _make_api_call
    http, parsed_response = self._make_request(
.venv/lib/python3.12/site-packages/botocore/client.py:1016: in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
.venv/lib/python3.12/site-packages/botocore/endpoint.py:119: in make_request
    return self._send_request(request_dict, operation_model)
.venv/lib/python3.12/site-packages/botocore/endpoint.py:202: in _send_request
    while self._needs_retry(
.venv/lib/python3.12/site-packages/botocore/endpoint.py:354: in _needs_retry
    responses = self._event_emitter.emit(
.venv/lib/python3.12/site-packages/botocore/hooks.py:412: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
.venv/lib/python3.12/site-packages/botocore/hooks.py:256: in emit
    return self._emit(event_name, kwargs)
.venv/lib/python3.12/site-packages/botocore/hooks.py:239: in _emit
    response = handler(**kwargs)
.venv/lib/python3.12/site-packages/botocore/retryhandler.py:207: in __call__
    if self._checker(**checker_kwargs):
.venv/lib/python3.12/site-packages/botocore/retryhandler.py:284: in __call__
    should_retry = self._should_retry(
.venv/lib/python3.12/site-packages/botocore/retryhandler.py:307: in _should_retry
    return self._checker(
.venv/lib/python3.12/site-packages/botocore/retryhandler.py:363: in __call__
    checker_response = checker(
.venv/lib/python3.12/site-packages/botocore/retryhandler.py:247: in __call__
    return self._check_caught_exception(
.venv/lib/python3.12/site-packages/botocore/retryhandler.py:416: in _check_caught_exception
    raise caught_exception
.venv/lib/python3.12/site-packages/botocore/endpoint.py:278: in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
.venv/lib/python3.12/site-packages/botocore/hooks.py:412: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
.venv/lib/python3.12/site-packages/botocore/hooks.py:256: in emit
    return self._emit(event_name, kwargs)
.venv/lib/python3.12/site-packages/botocore/hooks.py:239: in _emit
    response = handler(**kwargs)
moto/core/botocore_stubber.py:38: in __call__
    response = self.process_request(request)
moto/core/botocore_stubber.py:91: in process_request
    backend = backend_dict[DEFAULT_ACCOUNT_ID]["global"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = {}, region_name = 'global'

    def __getitem__(self, region_name: str) -> SERVICE_BACKEND:
        if region_name in self.keys():
            return super().__getitem__(region_name)
        # Create the backend for a specific region
        with backend_lock:
            if region_name in self.regions and region_name not in self.keys():
                super().__setitem__(
                    region_name, self.backend(region_name, account_id=self.account_id)
                )
            if region_name not in self.regions and allow_unknown_region():
                super().__setitem__(
                    region_name, self.backend(region_name, account_id=self.account_id)
                )
>       return super().__getitem__(region_name)
E       KeyError: 'global'

moto/core/base_backend.py:290: KeyError
```

**Comment by bblommers** [comment]
Hi @JoshLevyMN! I think this will require a manual change to get this to work - I don't see an easy way to automate this.

When generating the scaffolding, the last line in `models.py` creates a dict that will contain all the user-provided data:
```
bedrockagent_backends = BackendDict(AgentsforBedrockBackend, "bedrock-agent")
```
The second argument is called the `servicename`, and is used to determine in which regions this service is available:
```
boto3.Session().get_available_regions("bedrock-agent")
```

The problem is this particular service doesn't any regions configured - it returns an empty list. 
And we do expect a service to be available in *a* region - either in `us-east-1`, or in a made-up region called  `global` for global services like S3.
The KeyError basically means: This particular service isn't available in either `us-east-1` _or_ globally, so there's probably something wrong.

What we usually do is provide an alternative service that should return the correct list of regions. In this case we can just use `bedrock` instead. So if you change this line manually after the first scaffolding, everything should work again (both scaffolding other operations and running tests) :

`bedrockagent_backends = BackendDict(AgentsforBedrockBackend, "bedrock")`
