### ISSUE TITLE
AutoScalingGroup with CloudFormation is not able to delete stack

### ISSUE THREAD

**Issue by akashkiran-s** [getmoto/moto#7527]
Using cloudformation templates, I am trying to create an EC2::LaunchTemplate with AutoScalingGroup. Unfortunately this is failing on Moto.

### Steps to produce error

1. Start moto on localhost:5000
2. Create a test template file at `/path/to/test.template`
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Trying to create ec2 with auto scaling group",
  "Parameters": {
    "Subnets": {
      "Description": "Pass in the created subnet ids",
      "Type": "List<AWS::EC2::Subnet::Id>"
    },
    "StackName": {
      "Type": "String",
      "Description": "Unique stack name"
    }
  },
  "Resources": {
    "TestLaunchTemplate": {
      "Type": "AWS::EC2::LaunchTemplate",
      "Properties": {
        "LaunchTemplateName": {
          "Fn::Sub": "${AWS::StackName}-launch-template"
        },
        "LaunchTemplateData": {
          "BlockDeviceMappings": [
            {
              "DeviceName": "/dev/xvda",
              "Ebs": {
                "VolumeType": "gp3",
                "VolumeSize": "30",
                "DeleteOnTermination": "true",
                "Encrypted": "true"
              }
            }
          ],
          "ImageId": "ami-12c6146b",
          "InstanceType": "t3.micro"
        },
        "VersionDescription": "Initial Version"
      }
    },
    "ECSAutoScalingGroup": {
      "Type": "AWS::AutoScaling::AutoScalingGroup",
      "Properties": {
        "VPCZoneIdentifier": {
          "Ref": "Subnets"
        },
        "LaunchTemplate": {
          "LaunchTemplateId": { "Ref": "TestLaunchTemplate"},
          "Version": "$DEFAULT"
        },
        "CapacityRebalance": true,
        "MinSize": "1",
        "MaxSize": "10",
        "DesiredCapacity": "5"
      }
    }
  }
}

```
3. Create a VPC and Subnet using the below python script
```
def setup_networking(region_name="us-east-1"):
    ec2 = boto3.resource("ec2", region_name=region_name, endpoint_url='http://localhost:5000')
    vpc = ec2.create_vpc(CidrBlock="10.11.0.0/16")
    subnet1 = ec2.create_subnet(
        VpcId=vpc.id, CidrBlock="10.11.1.0/24", AvailabilityZone=f"{region_name}a"
    )
    subnet2 = ec2.create_subnet(
        VpcId=vpc.id, CidrBlock="10.11.2.0/24", AvailabilityZone=f"{region_name}b"
    )
    return {"vpc": vpc.id, "subnet1": subnet1.id, "subnet2": subnet2.id}

setup_networking("us-west-2")
```
4. Use the terminal for creating the stack. Pass the subnets as shown below. The stack should be created **without** an error
```
aws --debug --endpoint-url http://localhost:5000 cloudformation create-stack --stack-name test01 --template-body file:///path/to/test.template --parameters ParameterKey="Subnets",ParameterValue=subnet-33a55407\\,subnet-35a0a061 ParameterKey="StackName",ParameterValue="test01" --region us-west-2
```
5. Now try deleting this stack with the below command on terminal. This produces an error
```
aws --debug --endpoint-url http://localhost:5000 cloudformation delete-stack --stack-name test01 --region us-west-2
```
### Stacktrace 
```
Error on request:
Traceback (most recent call last):
  File "/path/to/my/moto/repo/moto/moto/cloudformation/parsing.py", line 893, in _delete_resource
    parsed_resource.delete(self._account_id, self._region_name)
AttributeError: 'LaunchTemplate' object has no attribute 'delete'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
  File "/path/to/my/moto/repo/moto/moto/moto_server/werkzeug_app.py", line 257, in __call__
    return backend_app(environ, start_response)
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/path/to/my/moto/repo/moto/venv/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/path/to/my/moto/repo/moto/moto/core/utils.py", line 112, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/path/to/my/moto/repo/moto/moto/core/responses.py", line 270, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/path/to/my/moto/repo/moto/moto/core/responses.py", line 478, in _dispatch
    return self.call_action()
  File "/path/to/my/moto/repo/moto/moto/core/responses.py", line 575, in call_action
    response = method()
  File "/path/to/my/moto/repo/moto/moto/cloudformation/responses.py", line 402, in delete_stack
    self.cloudformation_backend.delete_stack(name_or_stack_id)
  File "/path/to/my/moto/repo/moto/moto/cloudformation/models.py", line 1230, in delete_stack
    self.delete_stack(stack.stack_id)
  File "/path/to/my/moto/repo/moto/moto/cloudformation/models.py", line 1221, in delete_stack
    stack.delete()
  File "/path/to/my/moto/repo/moto/moto/cloudformation/models.py", line 538, in delete
    self.resource_map.delete()
  File "/path/to/my/moto/repo/moto/moto/cloudformation/parsing.py", line 887, in delete
    raise last_exception
  File "/path/to/my/moto/repo/moto/moto/cloudformation/parsing.py", line 876, in delete
    self._delete_resource(parsed_resource, resource_json)
  File "/path/to/my/moto/repo/moto/moto/cloudformation/parsing.py", line 900, in _delete_resource
    parse_and_delete_resource(
  File "/path/to/my/moto/repo/moto/moto/cloudformation/parsing.py", line 436, in parse_and_delete_resource
    resource_class.delete_from_cloudformation_json(
  File "/path/to/my/moto/repo/moto/moto/ec2/models/launch_templates.py", line 193, in delete_from_cloudformation_json
    backend.delete_launch_template(name, None)
  File "/path/to/my/moto/repo/moto/moto/ec2/models/launch_templates.py", line 246, in delete_launch_template
    tid = self.launch_template_name_to_ids.get(name)
TypeError: unhashable type: 'dict'
```

**Comment by akashkiran-s** [comment]
I think implementing a `delete()` method for the class `LaunchTemplate` should do the trick 
<img width="500" alt="Screenshot 2024-03-26 at 6 17 05 PM" src="https://github.com/getmoto/moto/assets/87519262/d3234fa9-d582-465e-a040-f6d076ad4e4e">

**Comment by rafcio19** [comment]
@bblommers I can take a look
