### ISSUE TITLE
KMS sign fails with alias ARN

### ISSUE THREAD

**Issue by 1001R** [getmoto/moto#8090]
During execution of

```python
@mock_aws
def main():
    kms: KMSClient = boto3.client("kms", region_name="eu-west-1")
    key = kms.create_key(
        KeyUsage="SIGN_VERIFY",
        KeySpec="ECC_NIST_P256",
    )
    key_id = key["KeyMetadata"]["KeyId"]
    kms.create_alias(
        AliasName=f"alias/foo",
        TargetKeyId=key_id,
    )
    kms.sign(
        KeyId=f"arn:aws:kms:eu-west-1:123456789012:alias/foo",
        MessageType="RAW",
        SigningAlgorithm="ECDSA_SHA_256",
        Message=bytes(8),
    )
```

an exception is raised:
```
Traceback (most recent call last):
  File "/home/phil/repos/cbcf4-cdk-library/src/moto_bug.py", line 27, in <module>
    main()
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/core/models.py", line 122, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/src/moto_bug.py", line 20, in main
    kms.sign(
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
          ^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/retryhandler.py", line 307, in _should_retry
    return self._checker(
           ^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
                       ^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/endpoint.py", line 278, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/core/botocore_stubber.py", line 38, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/core/botocore_stubber.py", line 88, in process_request
    status, headers, body = method_to_execute(
                            ^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/core/responses.py", line 290, in dispatch
    return cls()._dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/core/responses.py", line 501, in _dispatch
    return self.call_action()
           ^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/core/responses.py", line 587, in call_action
    response = method()
               ^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/kms/responses.py", line 645, in sign
    key_id, signature, signing_algorithm = self.kms_backend.sign(
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/kms/models.py", line 681, in sign
    key = self.describe_key(key_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/kms/models.py", line 381, in describe_key
    key = self.keys[self.get_key_id(key_id)]
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/repos/cbcf4-cdk-library/venv/lib64/python3.12/site-packages/moto/kms/models.py", line 398, in get_key_id
    if key_id.startswith("arn:") and ":key/" in key_id:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

It seems like the alias isn't resolved correctly when passed along as an ARN. Tried with Moto 5.0.13 and 5.0.14dev62 and Python 3.12.4.

**Comment by bblommers** [comment]
Thanks for raising this @1001R, and welcome to Moto! I've submitted a PR with a bugfix.

**Comment by 1001R** [comment]
Thanks for the quick fix!
